### PR TITLE
Organized Project

### LINKED ISSUE #5: Organize Project

### PR DESCRIPTION
**Pull request by Keffury1**
Closes #5

### CODE REVIEW

**Review by dimitribouniol — CHANGES_REQUESTED** [review]
Since you made this PR while the other one (#3) was still in the queue, you'll need to do the following:
- Make sure master is up to date (switch to master, pull, switch back to this branch)
- Rebase this branch off of master
- Force push it to replace what is in this PR with your cleaned up branch.

I also suggest you follow the instructions [here](https://github.com/LambdaSchool/ios-git-setup) to setup a global git ignore file, since you've inadvertently committed `.DS_Store` and `xcuserdata` files, which shouldn't be in your repo. After doing so, include a commit where you remove these files and include it with this PR.

**Review by Keffury1 — COMMENTED** [review]
Should be correct now.

**Comment by dimitribouniol** [comment]
The rebase didn't seem to remove the `Created Xcode Project.` commit from this branch. I can help you fix it at around ~4pm if you are available at that time.

**Comment by Keffury1** [comment]
Yes, I believe you're right. I have an appointment until 6pm PST if you're free to nail this down then.

**Comment by dimitribouniol** [comment]
After 6pm works for me!

**Pull request closed without merging**
